version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Entrenando modelo..."
      - python src/train.py
  post_build:
    commands:
      - echo "Modelo y transformador generados exitosamente."

artifacts:
  files:
    - model.pkl
    - transformer.pkl
