AWSTemplateFormatVersion: '2010-09-09'
Description: Proyecto CodeBuild para construir imagen Docker y subir a ECR

Parameters:
  ArtifactBucket:
    Type: String
    Description: Nombre del bucket S3 donde se almacenarán los artefactos
  CodeRepo:
    Type: String
    Description: URL HTTPS del repositorio GitHub (ej. https://github.com/user/repo.git)
  BranchName:
    Type: String
    Default: main
    Description: Rama del repositorio a construir

Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeBuildDockerECRServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildDockerECRPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:PutImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - s3:PutObject
                  - s3:GetObject
                Resource: "*"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: ml-model-lambda-build
      Description: Build project for ML model Docker image and push to ECR
      Source:
        Type: GITHUB
        Location: !Ref CodeRepo
        GitCloneDepth: 1
        BuildSpec: buildspec.yml
      SourceVersion: !Ref BranchName
      Artifacts:
        Type: S3
        Location: !Ref ArtifactBucket
        Packaging: ZIP
        Name: codebuild-output-artifacts
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: IMAGE_REPO_NAME
            Value: ml-model-lambda
          - Name: IMAGE_TAG
            Value: latest
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn

Outputs:
  CodeBuildProjectName:
    Description: Nombre del proyecto CodeBuild creado
    Value: !Ref CodeBuildProject
